# php satis dockerfile
FROM ubuntu:12.04
MAINTAINER me@ljf.me
RUN wget -O /etc/apt/sources.list http://mirror.ubuntu9.com/topmirror/sourceslist/topstable?`lsb_release -c | cut -f2`
RUN apt-get update -y
RUN apt-get upgrade -y
